---
- name: Configuration stockage workers
  hosts: worker_node
  become: true

  tasks:
    - name: Installer open-iscsi
      apt:
        name: open-iscsi
        state: present
        update_cache: yes

    - name: Activer iscsid
      systemd:
        name: iscsid
        state: started
        enabled: true

    - name: Formater le disque
      filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

    - name: Créer dossier longhorn
      file:
        path: /mnt/longhorn
        state: directory

    - name: Ajouter entrée fstab
      mount:
        path: /mnt/longhorn
        src: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
        fstype: ext4
        opts: defaults,nofail,x-systemd.automount,x-systemd.device-timeout=10s
        state: mounted
